### PR TITLE
Npcarney kgodiwal

### PR DESCRIPTION
**Pull request by npcarney**
Added header comments to each .java class, set private attributes to ServerSolution.java to the map and fileName, reordered Saveing.java class, andd made ServerSolution a public class.

### CODE REVIEW

**Comment by paulsoiya** [comment]
Looks like you did a great job fixing the issues.

**Comment by smcelroy** [comment]
Your solution to renaming the state enum to all caps was excellent, I approve of this change.

**Comment by npcarney** [comment]
I should have mentioned what issue was resolved with each commit

**Comment by npcarney** [comment]
I just refactored the enum state to STATE to make sure no instances were missed. I was better than changing it manually.

**Pull request closed without merging**
